### ISSUE TITLE
A technical doubt

### ISSUE THREAD

**Issue by GopiRajuMatta** [WU-CVGL/BeNeRF#4]
Hello @pianwan!

Thank you for nice work and many congratulations..

In this framework, what ensures that each image should be sharp and it's a deblurred version of input? It might happen set of rendered images(which are blurry), when we average them can still ensure output will be as blurry as input..

Can you please clarify on this.

Thank you
Gopi

**Comment by pianwan** [comment]
Thank you for your question.

The answer is **geometric constraints**.

To clarify:

The geometric constraints of this 3D scene should be satisfied to ensure the consistency of rendering from different camera poses (e.g. some rays from front, some rays from left side, some rays from right side). If all the rendered images (rays) are blurry, the training loss will be very high. You can find more details about this in the BADNeRF and NeRF papers.

In our BeNeRF, the sharpness of the scene is further ensured by the event stream. With RGB loss only, it would be challenging to construct a 3D scene from a very short trajectory (the geometric constraint is not strong enough for optimization, so what you described may happen). However, the additional information provided by the event stream makes it possible to build the sharp 3D scene (i.e. the event loss mentioned in our paper).

If you have any further questions, please don’t hesitate to reach out.

**Comment by GopiRajuMatta** [comment]
Thank you so much for your detailed explanation...

I am trying a similar framework with Gaussian Splatting, but my output(each image) is not clear(deblurred), each image is having artifacts but the blur image(rendered blur image) when I sum up render ones is giving input blur image, even with PSNR 60dB or so.. this I tried with 5 virtual cameras. When I tried to increase no. of virtual cameras, virtual cameras are drifting in zigzag fashion. For pose optimization, I am not using B-splines, is that the issue for drifting of camera locations? Also, for some reason, event loss is contributing not much, if I keep factor 2 for event loss, framework is not converging at all. Also, if I use only event loss, output is fully blank even with BeNeRF..

Help and suggestions in this regard are highly appreciated.

Thank you
Gopi

**Comment by pianwan** [comment]
> Thank you so much for your detailed explanation...
> 
> I am trying a similar framework with Gaussian Splatting, but my output(each image) is not clear(deblurred), each image is having artifacts but the blur image(rendered blur image) when I sum up render ones is giving input blur image, even with PSNR 60dB or so.. this I tried with 5 virtual cameras. When I tried to increase no. of virtual cameras, virtual cameras are drifting in zigzag fashion. For pose optimization, I am not using B-splines, is that the issue for drifting of camera locations? Also, for some reason, event loss is contributing not much, if I keep factor 2 for event loss, framework is not converging at all. Also, if I use only event loss, output is fully blank even with BeNeRF..
> 
> Help and suggestions in this regard are highly appreciated.
> 
> Thank you Gopi

You may check out BAD-Gaussians if you train with multiple images without event loss.
https://github.com/WU-CVGL/BAD-Gaussians

For our BeNeRF, I think it should undoubtedly work if you only change from NeRF to Gaussians.

**Comment by GopiRajuMatta** [comment]
Can we shortly meet online when you are available? It will be very helpful.. I am working on this problem, but struct with this for quite a time.  I guess, you will be very busy, but if you can spare sometime, it will be really great..

**Comment by akawincent** [comment]
@GopiRajuMatta 

Thank you for reaching out! I'd be happy to set up an online meeting to discuss this further. 

Could you please let me know which **software you prefer to use for the meeting** (e.g., Zoom, Google Meet, etc.) and **suggest a few dates and times** that work for you? 
The **author of [BAD-Gaussian](https://github.com/WU-CVGL/BAD-Gaussians) will also be joining us**, so we’ll try to accommodate everyone’s schedules. 

Looking forward to helping you with this!

**Comment by GopiRajuMatta** [comment]
Thank you so much for your positive reply!

Google meet should be fine.. 
Dates and times:  13/11/24(Wednesday), 9am to 6pm(IST)
                                14/11/24(Thursday), 9am to 3pm(IST)
                                15/11/24(Friday), 9am to 2pm(IST)
                                
Thank you once again..

**Comment by akawincent** [comment]
> Thank you so much for your positive reply!
> 
> Google meet should be fine.. Dates and times: 13/11/24(Wednesday), 9am to 6pm(IST) 14/11/24(Thursday), 9am to 3pm(IST) 15/11/24(Friday), 9am to 2pm(IST)
> 
> Thank you once again..

Cool. Can you tell me you work email address? I'll send you the meeting ID and time later.

**Comment by GopiRajuMatta** [comment]
Thank you.

My email id : ee17d021@smail.iitm.ac.in

Thank you
Gopi
