### ISSUE TITLE
Request for Pretrained Models

### ISSUE THREAD

**Issue by GopiRajuMatta** [WU-CVGL/BeNeRF#5]
Hello!

Can you also please open source pre-trained models for the real datasets and synthetic datasets?

Thank you
Gopi

**Comment by akawincent** [comment]
We are planning to release the pre-trained model weights publicly. 

As you know, our model is designed such that each pre-trained model corresponds to a single image. We’ve run BeNeRF on three datasets totaling 850 images, so we have 850 pre-trained models in total. Organizing this will take some time. If you need a specific model urgently, please let us know which dataset and image you’re interested in, and I can help retrieve the corresponding weights for you.

Hope this can help you.

**Comment by GopiRajuMatta** [comment]
Thank you so much for your positive reply.

I need models of real dataset(e2nerf_real).
**dataset : image**
camera : 075.jpg
lego : 020.jpg
letter : 065.jpg
plant : 020.jpg
toys : 095.jpg

Thank you
Gopi

**Comment by akawincent** [comment]
Done.
